---

- hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
  - add_host: name=testboot.lxd groups=testboot
  - add_host: name=testbootalpine.lxd groups=testboot lxd_alias=alpine/3.4/amd64
  roles:
  - .

- hosts: testboot
  tasks:
  - shell: uname -a
